services:
  labeler:
    build: .
    container_name: tt-ball-labeler
    environment:
      - LABEL_DATA_DIR=/data
      - APP_ROOT_PATH=
    volumes:
      - ./data:/data
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: tt-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - labeler
    restart: unless-stopped

volumes:
  caddy_data: {}
  caddy_config: {}
