name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Copy compose file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          port: ${{ secrets.IONOS_SSH_PORT || 22 }}
          source: "compose.deploy.yaml"
          target: ${{ secrets.PROJECT_DIR }}

      - name: SSH deploy on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          key: ${{ secrets.IONOS_SSH_KEY }}
          port: ${{ secrets.IONOS_SSH_PORT || 22 }}
          script: 
            set -e
            cd "${{ secrets.PROJECT_DIR }}"
            mkdir -p data
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker compose -f compose.deploy.yaml pull
            docker compose -f compose.deploy.yaml up -d --remove-orphans
            docker image prune -f
