name: Deploy Dual Apps to IONOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Ball Analyzer
      uses: docker/build-push-action@v5
      with:
        context: ./ball-web-analyzer
        file: ./ball-web-analyzer/webapp/Dockerfile-fastapi
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ball-web-analyzer:latest
    
    - name: Deploy to IONOS Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.IONOS_HOST }}
        username: ${{ secrets.IONOS_USER }}
        key: ${{ secrets.IONOS_SSH_KEY }}
        script: |
          cd /root/tt-apps
          git pull origin main
          docker compose -f compose.ionos.yaml pull
          docker compose -f compose.ionos.yaml down
          docker compose -f compose.ionos.yaml up -d
          docker system prune -f
